package peterfajdiga.sszj.sets;

import java.util.HashMap;
import java.util.Map;

import peterfajdiga.sszj.R;

public class Sets {
    private Sets() {}

    // TODO: put in a raw resource file
    public static final Set[] SETS = new Set[] {
        new Set("Osebe", R.drawable.sets_1,
            "babica", "boter", "bratranec", "brat", "človek", "deček", "dedek", "dekle", "dojenček", "družina", "dvojčka", "fant",
            "gospa", "gospod", "gospodar", "hči", "ime", "lastnik", "ljudje", "mati", "mlad", "mlajši", "množica", "moj", "moški",
            "mož", "najin", "naš", "nečakinja", "nečak", "nekdo", "nihče", "njegov", "njen", "njihov", "njun", "nobeden", "oče",
            "odrasli", "odraščanje", "odraščati", "ona", "oseba", "osebnost", "otroci", "otrok", "poroka", "priimek", "prijatelj",
            "razveza", "reja", "rejnica", "sestra", "sestrična", "sin", "sorodnik", "sosed", "stara mati", "starejši", "stari oče",
            "starši", "star", "stric", "teta", "tisto", "to", "trojčki", "tvoj", "vajin", "vaš", "vnuk", "vsi", "žena", "ženska"
        ),
        new Set("Delo", R.drawable.sets_2,
            "delati", "delavnica", "delo", "firma", "imajo", "imamo", "imam", "imaš", "imata", "imate", "imava", "ima", "industrija",
            "iskati", "izbrati", "izdelek", "izguba", "izgubiti", "izkoriščati", "najti", "napraviti", "narediti", "obdržati", "obrt",
            "odpustiti", "podjetje", "pojav", "pojaviti se", "pripraviti", "proizvodnja", "pustiti", "služba", "sprejeti", "storiti",
            "stroj", "tovarna", "zamenjati", "zaposliti", "zgoditi se"
        ),
        new Set("Opravila", R.drawable.sets_3,
            "brisati", "brusiti", "čistiti", "frizirati", "gasiti", "grabiti", "grablje", "graditi", "kositi", "krmiti", "krojiti",
            "kuriti", "likalnik", "likati", "lopata", "lopatiti", "lupiti", "molsti", "motika", "nabirati", "obdelovati", "obesiti",
            "odpreti", "okopavati", "orati", "piliti", "plug", "pobirati", "počistiti", "položiti", "pometati", "popraviti",
            "pospraviti", "postaviti", "potegniti", "prati", "preseliti", "prižgati", "puliti", "razmetati", "rezati", "saditi", "sejati",
            "sekati", "sekira", "sesalnik", "sesati", "srp", "striči", "šivati", "točiti", "ugasniti", "viseti", "vleči", "vrteti",
            "zalivati", "zapreti", "zaprto", "zavezati", "žaga", "žagati", "žeti"
        ),
        new Set("Poklici", R.drawable.sets_4,
            "administrator", "berač", "čistilka", "čuvati", "delavec", "dijak", "direktor", "gasilec", "gospodinja", "kapitan",
            "ključavničar", "kmečki", "kmet", "knjigovez", "kopati", "kovinar", "kralj", "lopov", "mehanik", "mesar", "mizar", "mornar",
            "natakar", "novinar", "oblič", "oficir", "pastir", "paziti", "pek", "pilot", "pisalni stroj", "pleskar", "pleskati", "poklic",
            "policist", "postati", "prodajalec", "prodajati", "profesor", "računovodja", "ravnatelj", "retušer", "rop", "ropar",
            "ropati", "rudar", "sekretar", "slaščičar", "slikati", "strojnik", "stroka", "strokoven", "šef", "šivilja", "tajnik",
            "tat", "tatvina", "tehnični", "tehnik", "telefonist", "tipkati", "trgovec", "učenec", "učenje", "učiti se", "ukrasti",
            "upokojenec", "upokojiti se", "vajenec", "vladar", "voditi", "vodja", "vojak", "vratar", "vzgojitelj", "zidar", "zidati",
            "zlatar"
        ),
        new Set("Vprašalnice", R.drawable.sets_5,
            "ako", "ali", "čemu", "če", "čigav", "kaj", "kako", "kakšen", "kam", "kateri", "kdaj", "kdo", "kje", "koliko", "odkod",
            "zakaj"
        ),
        new Set("Osebni zaimki s pomožnikom", R.drawable.sets_6,
            "jaz", "meni", "mi", "midva", "nam", "nama", "njemu", "njim", "njima", "on", "ona je", "onadva", "oni", "sem", "si", "smo",
            "so", "sta", "ste", "sva", "tebi", "ti", "vam", "vama", "vi", "vidva"
        ),
        new Set("Čas", R.drawable.sets_7,
            "april", "avgust", "bodočnost", "budilka", "čas", "četrtek", "dan", "danes", "datum", "december", "februar", "gotovo",
            "januar", "jesen", "julij", "junij", "jutri", "kmalu", "koledar", "končano", "končati", "konec", "kratko", "lani", "letos",
            "maj", "marec", "mesec", "mesečno", "minuta", "naslednji", "nedelja", "nekoč", "nikoli", "noč", "november", "odlašati",
            "oktober", "opoldne", "opolnoči", "petek", "pojutrišnjem", "poletje", "pol", "pomlad", "ponedeljek", "ponoči", "ponoviti",
            "ponovno", "popoldne", "potem", "pozneje", "pozno", "pravkar", "pred kratkim", "predvčerajšnjim", "prej", "prestaviti",
            "preteklo", "preteklost", "prosto", "ročna ura", "samo", "sedaj", "sedanjost", "sekunda", "september", "skoraj", "sobota",
            "spet", "sreda", "stalno", "še", "še enkrat", "teden", "torek", "ura", "včasih", "včeraj", "večkrat", "vedno", "vsak dan",
            "vsak", "vso noč", "začasno", "začeti", "zamuditi", "zgodaj", "zima", "zjutraj", "zvečer", "že"
        ),
        new Set("Mišljenje", R.drawable.sets_8,
            "abstrakten", "ampak", "dovoliti", "fakulteta", "fantazirati", "inteligenten", "izkušnja", "izmisliti si", "izumiti", "izum",
            "misel", "misliti", "mnenje", "mogoče", "motiti", "načrtovati", "ne vem", "odločiti", "odločiti se", "odvisno", "pameten",
            "pazljiv", "pojem (kot abstraktnost)", "poskus", "pozabiti", "poznati", "pozornost", "praksa", "pravilno", "prav",
            "premisliti si", "premišljevati", "prepričati", "previden", "primerjati", "problem", "projekt", "razum", "razumeti", "res",
            "sanjati", "sanje", "skrbeti", "skrbeti za", "skrb", "spomin", "spomniti se", "spremeniti", "teorija", "toda", "uganiti",
            "uganka", "ugotoviti", "upati", "vedeti", "vem", "ve", "veš", "vplivati", "vpliv", "vseeno", "vzgoja", "vzrok", "zdeti se",
            "zmotiti se", "znam", "znati"
        ),
        new Set("Čustva, volja in občutki", R.drawable.sets_9,
            "agresivnost", "bahati se", "baraba", "bati se", "bedak", "bes", "besen", "bled", "božati", "butec", "butelj", "čuden",
            "čudno", "čutiti", "divji", "dober", "dobra volja", "dobričina", "dolgočasen", "dolgočasiti se", "dolžnost",
            "domišljav", "dragi (ljubkovalno)", "enostavno", "gabiti se", "gledati", "gnus", "grob", "groza", "hinavec", "hoteti",
            "hudoben", "hudo", "hud", "hvala", "hvaležnost", "iskren", "izgovarjati se", "izgovor", "izvoli", "jeza", "jok", "jokati",
            "karakter", "lagati", "laž", "len", "ljubezen", "ljubosumen", "ljubosumnost", "maščevanje", "maščevati", "mrk", "mržnja",
            "mučiti", "nalašč", "namenoma", "napadalnost", "nasilen", "navdušen", "ne maram", "ne marati", "ne morem", "nesreča",
            "neumen", "nevoščljiv", "nežen", "nočem", "občudovati", "občutek", "občutljiv", "obnašati se", "obžalovati",
            "oddahniti si", "odgovornost", "odkritosrčen", "odpor", "ogaben", "opaziti", "oprostiti", "osamljen", "otožen",
            "počutiti se", "pogum", "poljub", "pomiriti se", "ponos", "poreden", "pošten", "potrpeti", "prebledeti", "preprost",
            "presenečenje", "presenetiti", "prezirati", "prezir", "priden", "prijazen", "prijaznost", "prijeten", "pritisk",
            "privlačnost", "rad", "rad imeti", "radoveden", "razburjenje", "razjeziti se", "razočaran", "razočarati", "resen",
            "resnica", "sebičnost", "simpatičen", "siten", "skopuh", "skopuški", "skromen", "slaba volja", "smeh", "smešen", "smola",
            "smrkavec", "sovraštvo", "sovražiti", "spoštovanje", "spoštovati", "sramežljivost", "sramovati se", "sreča", "srečen",
            "srečno", "strah", "strahopeten", "strpnost", "sum", "sumiti", "sumničav", "surov", "tolažiti", "trmast", "trpeti",
            "uničiti", "ustrašiti se", "utrujenost", "užaljen", "v redu", "varati", "važiti se", "veselje", "vesel", "vest", "videti",
            "vljuden", "volja", "všeč", "vzpodbuda", "vzpodbujati", "zadovoljstvo", "zadrega", "zaljubljen", "zamera", "zameriti",
            "zaničevati", "zardeti", "zaupanje", "zaupati", "značaj", "zvest", "žal", "žalost", "želeti", "živahen", "živčen"
        ),
        new Set("Telo", R.drawable.sets_10,
            "bos", "brada", "brki", "čelo", "dlan", "glava", "grlo", "hrbet", "hrbtenica", "jezik", "koleno", "komolec", "lasje", "lice",
            "mižati", "noga", "noht", "nos", "obrvi", "oko", "pest", "peta", "pleša", "prsti", "rama", "roka", "slina", "solza", "srce",
            "uho", "usta", "ustnica", "vrat", "zobje", "žulj"
        ),
        new Set("Medicina in bolezni", R.drawable.sets_11,
            "aids", "alkoholizem", "ambulanta", "avdiogram", "baterija", "blato", "boleti", "bolezen", "bolniški", "bolnišnica",
            "bruhati", "cepljenje", "cigara", "cigareta", "debel", "diagnoza", "dremati", "droga", "drogirati se", "gluh", "gluhonem",
            "gripa", "injekcija", "invalid", "izvid", "kaditi", "kajenje", "kakati", "kapljice", "kašelj", "kihati", "kirurgija", "kost",
            "koža", "kri", "lekarna", "lulati", "medicina", "medicinska sestra", "meningitis", "menstruacija", "mišica",
            "možganska kap", "mumps", "naglušen", "nahod", "nalezljivo", "napad", "negovati", "nem", "nervoza", "nosečnost", "obraz",
            "oddih", "omamljen", "operacija", "ORL", "ošpice", "otečeno", "oteklina", "pijan", "pik", "pljuvati", "počitek",
            "počivati", "pokvariti", "prebava", "pregled", "pregledati", "prehlad", "prva pomoč", "psiha", "psihologija", "rdečke",
            "recept", "rentgen", "roditi", "rojstvo", "seks", "slep", "slišati", "slišeč", "sluh", "smrt", "spolni odnos", "sposoben",
            "srbeti", "srčna kap", "strup", "ščipati", "škiliti", "tableta", "telo", "temperatura (pri bolezni)", "termometer",
            "ubiti", "udariti se", "udariti", "umoriti", "umor", "umreti", "urezati se", "urin", "vitek", "vnetje", "zalivka", "zaspan",
            "zaspati", "zbuditi koga", "zbuditi se", "zdrav", "zdravilišče", "zdravilo", "zdraviti", "zdravje", "zdravnik",
            "zdravniški", "zehati", "zlomiti", "zlom", "znanost", "zobozdravnik", "živci", "živeti", "življenje"
        ),
        new Set("Nega", R.drawable.sets_12,
            "brisača", "britev", "briti", "česati", "frizura", "glavnik", "kopati se", "krema", "lak za lase", "lak za nohte", "mazati",
            "milo", "negovati se", "obriti", "ostriči", "parfum", "pinceta", "posoda", "puder", "rdečilo", "robec", "striči lase",
            "šminka", "tuširati se", "tuš", "umivalnik", "umivati se", "umivati si lase", "umivati si obraz", "umivati si roke",
            "umivati si zobe", "vata", "zobna krema", "zobna krtačka"
        ),
        new Set("Narava", R.drawable.sets_13,
            "Afrika", "Amerika", "Avstralija", "Azija", "bliskanje", "blisk", "bliskati se", "bodica", "breg", "burja", "deblo", "dežela",
            "dež", "dim", "dolina", "drevje", "drevo", "Evropa", "gnezdo", "gnoj", "gora", "goreti", "gozd", "grm", "grmovje", "grozdje",
            "hrib", "izvir", "jablana", "jama", "jezero", "jug", "Južna Amerika", "kamen", "kepa", "klanec", "kmetija", "kopriva",
            "korenine", "lakota", "led", "lipa", "list", "luknja", "luna", "mavrica", "megla", "mesto", "morje", "mrak", "nagelj",
            "narava", "nebo", "nevihta", "obala", "oblak", "obzorje", "ogenj", "otok", "ovijalka", "ovijati se", "planina", "ploha",
            "pokrajina", "polje", "poplava", "pot", "potok", "potres", "površina", "požar", "premog", "prepih", "puščava", "rasti",
            "ravnina", "reka", "rja", "roža", "sadovnjak", "senca", "sever", "Severna Amerika", "skala", "slap", "smreka", "sneg",
            "snežiti", "sonce", "strmina", "strmo", "suša", "svetlo", "svet", "svetloba", "šumeti", "šum", "toča", "trava", "travnik",
            "trd", "trgatev", "trta", "valovi", "vas", "veja", "venec", "vesolje", "veter", "voda", "vreme", "vrh", "vroče", "vročina",
            "vrt", "vulkan", "vzhod", "zahod", "zemlja", "zora", "zrak", "zrno", "zvezda", "zvok", "žarek"
        ),
        new Set("Živali", R.drawable.sets_14,
            "bik", "bolha", "dlaka", "gams", "golob", "govedo", "jelen", "jež", "kača", "kamela", "kenguru", "kljun", "kobilica",
            "kokoš", "komar", "konj", "koza", "krava", "krila", "krokodil", "krt", "lajati", "lev", "lisica", "mačka", "medved",
            "metulj", "miš", "mravlje", "muhe", "nosorog", "opica", "orel", "osel", "ovca", "pajek", "papiga", "pav", "perut", "pes",
            "pikapolonica", "pingvin", "polž", "povodni konj", "prašič", "ptič", "rep", "riba", "rog", "slon", "sova", "srna",
            "štorklja", "tele", "tiger", "uš", "veverica", "volk", "zajec", "zebra", "zmaj", "želva", "žirafa", "žival", "živina"
        ),
        new Set("Gibanje", R.drawable.sets_15,
            "bežati", "čakati", "gibati se", "hoditi", "iti", "izgini", "izstopiti", "izvoz", "jahati", "klečati", "korakati",
            "ležati", "lumpati", "marš", "nesti", "obrniti se", "obrniti", "oditi", "ostati", "ozirati se", "pasti", "plesati",
            "plezati", "pojaviti", "pojdi", "položaj", "potepati se", "prinesti", "priti", "sedeti", "skakati", "skočiti", "skok",
            "slediti", "srečati", "stati", "stopiti", "ujeti", "umakniti", "ustaviti", "uvoz", "vesti se", "voziti (avto)", "vrniti",
            "vrniti (meni)", "vrniti (nekomu)", "vrniti se", "vstati (iz postelje)", "vstati", "vstopiti", "zaleteti se", "zasledovati"
        ),
        new Set("Smer", R.drawable.sets_16,
            "asfalt", "čez", "drog", "gladina", "iz", "kol", "križišče", "mimo", "naravnost", "ob", "ovinek", "po", "poleg", "prehod",
            "pri", "ravno", "smer", "ulica", "vstop", "za", "zadaj", "zraven"
        ),
        new Set("Potovanje", R.drawable.sets_17,
            "avto", "avtobus", "avtokamp", "avtostop", "bencin", "cesta", "dopust", "garderoba", "gost", "helikopter", "izlet", "kamp",
            "karta", "kompas", "kovček", "ladja", "letalo", "leteti", "motor", "muzej", "nahrbtnik", "obisk", "odpotovati", "ogled",
            "park", "parkirišče", "peš", "počitnice", "postaja", "potni list", "potnik", "potovalka", "potovanje", "potovati",
            "pripotovati", "promet", "prometni znak", "prtljaga", "raketa", "razgled", "razstava", "rekreacija", "rešilni avto",
            "rezervacija", "rezervirano", "sejem", "semafor", "spraviti", "sprehod", "šofer", "šotor", "taksi", "tir", "torba",
            "tovornjak", "tračnice", "traktor", "turist", "vlak", "vlečnica", "voznik", "vožnja", "vzpenjača", "zaseden", "zasedeno",
            "železniška postaja"
        ),
        new Set("Bivalni prostori in pohištvo", R.drawable.sets_18,
            "balkon", "blazina", "blok", "cedilo", "cev", "dežnik", "dnevna soba", "dnevno", "domač", "domovina", "dom", "drva",
            "dvigalo", "elektrika", "fotografija", "garaža", "grad", "hiša", "hladilnik", "hlev", "hodnik", "internat", "izhod",
            "jedilnica", "jesti", "klet", "ključ", "kljuka", "kopalnica", "košara", "krtača", "krtačiti", "kuhinja", "lestev", "luč",
            "metla", "miza", "mreža", "nadstropje", "nikjer", "nositi (na sebi)", "nositi (v roki)", "noter", "notri", "obešalnik",
            "odeja", "odpadki", "ogledalo", "ograja", "okno", "okvir", "omara", "omarica", "opeka", "otroška soba", "parket", "pepelnik",
            "plin", "podstrešje", "pohištvo", "pomivalni stroj", "pomivati", "postelja", "potrkati", "pralni stroj", "pritličje",
            "prostor", "prt", "rjuha", "shramba", "soba", "spalnica", "stanovanje", "stena", "stikalo", "stolpnica", "stol", "stranišče",
            "streha", "strop", "sveča", "šivalni stroj", "škatla", "štedilnik", "tapeta", "tla", "vaza", "vece (wc)", "vedro",
            "veriga", "vhod", "vključiti", "vrata", "vreča", "vrv", "vtičnica", "vžigalica", "wc (vece)", "zgradba", "zid", "zvonec",
            "žarnica"
        ),
        new Set("Oblačila", R.drawable.sets_19,
            "bala", "blago", "bluza", "bombaž", "bunda", "copati", "čevlji", "elastično", "elastika", "gumb", "halja", "hlače",
            "jakna", "jopica", "kapa", "kavbojke", "kravata", "krilo", "kvačkati", "majica", "material", "moda", "moderen", "nit",
            "nogavice", "obleči", "obleka", "obuti", "ovratnik", "perilo", "plašč", "plesti", "pomeriti", "prstan", "puli", "pulover",
            "raztrgano", "rokavice", "rokav", "ruta", "sandali", "sezuti", "sleči", "srajca", "stvar", "sukanec", "suknjič", "superge",
            "svila", "šal", "škornji", "trak", "uhan", "usnje", "verižica", "volna", "volneno", "zadrga", "zaponka", "žabe", "žamet",
            "žep"
        ),
        new Set("Hrana in pijača", R.drawable.sets_20,
            "alkohol", "banana", "bife", "bonbon", "borovnice", "breskev", "cmok", "cvetača", "cvet", "čaj", "čebula", "česen",
            "češnje", "čevapčiči", "čokolada", "dober tek", "duda", "figa", "fižol", "goba", "golaž", "gostilna", "grah", "grenko",
            "gristi", "hotel", "hrana", "hren", "hrenovka", "hruška", "jabolčni zavitek", "jabolko", "jagoda", "jajce", "juha", "kava",
            "kislo", "kis", "klobasa", "kokakola", "kompot", "konzerva", "korenje", "koruza", "kosilo", "kostanj", "kozarec", "krof",
            "krompir", "krožnik", "kruh", "krvavica", "kuhati", "kumara", "lačen", "lešnik", "limona", "lizati", "lonec", "lubenica",
            "makaroni", "malica", "marelica", "marmelada", "maslo", "mast", "maščoba", "meso", "mešati", "mleko", "moka", "namazati",
            "nož", "ocvirki", "ocvrt krompirček (pomfrit)", "okusiti", "okusno", "okus", "olje", "omaka", "oreh", "palačinka",
            "panirati", "paprika", "paradižnik", "pečenka", "peči", "pesa", "pijača", "piknik", "piškot", "piti", "pivo",
            "pizza, pica", "pohati (cvreti)", "pojesti", "polenta", "pomaranča", "pomfrit (ocvrt krompirček)", "ponuditi", "poper",
            "poskusiti", "potica", "pršut", "puding", "razdeliti", "repa", "restavracija", "riž", "sadje", "salama", "sendvič", "sir",
            "sit", "skleda", "skodelica", "skuta", "sladko", "sladkor", "sladoled", "sliva", "smetana", "smrad", "smrdeti", "sok",
            "solata", "sol", "steklenica", "streči", "strgati", "svaljki", "šampanjec", "špageti", "špinača", "štruca", "šunka",
            "tekočina", "testenine", "torta", "uživati", "večerja", "vilice", "vino", "višnje", "vonjati", "whisky (viski)", "zajtrk",
            "zaklati", "zamašek", "zamašiti", "zelenjava", "zelje", "zrezek", "žejen", "žemlja", "žganci", "žganje", "žlica",
            "žvečilni gumi"
        ),
        new Set("Komunikacija", R.drawable.sets_21,
            "anketa", "beseda", "časopis", "čeprav", "čestitati", "čitati", "čuditi se", "da", "diaprojektor", "dirigirati",
            "diskusija", "dokaz", "dokazati", "določiti", "dopisovanje", "dopisovati se", "ekran", "enako", "enoročna abeceda", "film",
            "fotografirati", "glasba", "glas", "gledališče", "govoriti", "govor", "grafoskop", "ideja", "igralec", "igrati", "in",
            "informacija", "intervju", "je", "kamera", "kaseta", "kino", "klepetati", "klicati", "knjiga", "knjižnica", "komunikacija",
            "kopija", "kot", "kretnja", "kričati", "kritika", "kritik", "kritizirati", "magnetofon", "mahati", "metoda", "motnja",
            "način", "nadaljevanka", "nadaljevati", "nalepka", "napis", "naročiti", "nasvet", "nasvidenje", "ne", "ni", "novice",
            "obljubiti", "obvestilo", "obvestiti", "oddaja", "odgledovanje", "odgledovati", "odgovoriti", "odgovor", "oglasiti se",
            "opozoriti", "opravljati", "osvetliti", "ovirati", "pečat", "peti", "petje", "pisanje", "pisati", "pisava", "pismo",
            "podatki", "podnaslov", "pogovarjati se", "pogovor", "pojasniti", "pokazati", "poklicati", "poslušati", "posvet", "pošta",
            "potrditi", "povabiti", "povedati", "pozdraviti", "pozdrav", "pozor", "pravljica", "predstaviti", "preložiti", "prepirati se",
            "prepis", "prepovedati", "preprečiti", "prevajalec", "prevajati", "prevod", "pripovedka", "pripovedovati", "pritožba",
            "pritožiti se", "priznati", "računalnik", "radio", "razglednica", "razgovor", "razlagati", "razpravljati",
            "reči (povedati)", "revija", "seveda", "seznam", "slika", "slušni aparat", "snemati", "spogledovati se", "sporočiti",
            "spraševati", "srečati se", "svetovati", "škoda", "tajiti", "telefon", "telefonirati", "telegram", "televizija", "test",
            "tisk", "tiskati", "tolmač", "tudi", "učitelj", "ukazati", "vabilo", "vabiti", "verjeti", "videokaseta", "video", "vpiti",
            "vpitje", "vprašanje", "vprašati", "zagotoviti", "zahtevati", "zahteva", "zamolčati", "zanikati", "zapis", "zaslon", "zato",
            "zavpiti", "zdravo", "zgodba", "znak", "znamka"
        ),
        new Set("Izobraževanje", R.drawable.sets_22,
            "barvati", "barvice", "besedilo", "biologija", "bonton", "črta", "dejstvo", "dežurni", "diploma", "disciplina", "dobro",
            "dopolniti", "dovoljenje", "dražiti", "ekskurzija", "fizika", "geografija", "gimnazija", "grafika", "inteligenca",
            "izobrazba", "izobraževanje", "izpit", "izvijač", "kemični svinčnik", "kemija", "kladivo", "klešče", "klicaj",
            "kontrola", "kontrolna naloga", "kovinarstvo", "kovina", "kuli", "lasten", "lepilni trak", "lepilo", "lepiti", "lepljiv",
            "lesarstvo", "letnik", "manjkati", "matematika", "matura", "mir", "na primer", "načrt", "nagajati", "nalivno pero", "naloga",
            "naslov", "neopravičeno", "nezadostno", "oblika", "obvladati", "ocena", "oddelek", "odlično", "odmor", "odsoten", "oklepaj",
            "olika", "opomin", "opomniti", "opravičilo", "opravičiti", "osnova", "osnovna šola", "oster", "ovira", "ovitek", "papir",
            "pero", "pika", "plan", "plastika", "podpisati", "poglavje", "pohvala", "poklicna šola", "posnemati", "potrdilo",
            "potruditi se", "poučevati", "prav dobro", "predmet", "primer", "prisoten", "program", "računalništvo", "radirati",
            "raziskovanje", "razred", "selotejp", "seminar", "slovenščina", "slovnica", "sošolec", "sprejem", "spričevalo", "srednja",
            "srednja šola", "stavek", "steklo", "strog", "svinčnik", "šestilo", "šilček", "škarje", "šola", "štipendija",
            "študij", "študirati", "tečaj", "tekstil", "tekst", "temelj", "tolči", "ubogati", "učbenik", "uči me", "učilnica",
            "učim se", "učiti", "univerza", "urnik", "usposabljanje", "ustanova", "uvod", "vijak", "višja šola", "višji", "vprašaj",
            "vprašalnik", "vrtec", "vsebina", "vzorec", "začetek", "zadostno", "zahvaliti se", "zavod", "zemljepis", "zgodovina",
            "zvezek"
        ),
        new Set("Družbena ureditev", R.drawable.sets_23,
            "ambasada", "član", "delegat", "demokracija", "demokratično", "demonstracija", "društvo", "družba", "država", "funkcija",
            "kolektiv", "komisija", "konflikt", "kongres", "krajevna skupnost", "liberalno", "mednarodno", "minister", "nadzorovati",
            "narod", "navada", "navadno", "občina", "običajno", "oblast", "odnos", "odstop", "organizacija", "organizirati", "parlament",
            "področje", "politika", "ponavadi", "poslanec", "pravilnik", "predsednik", "predstavnik", "republika", "revolucija",
            "samostojnost", "sestanek", "situacija", "sklep", "skupina", "skupnost", "skupščina", "spor", "stavka",
            "stranka (politična)", "ureditev", "urediti", "urejeno", "ustava", "veleposlaništvo", "vlada", "volitve", "zaključek",
            "zakon", "zastava", "zveza", "žig", "žigosati"
        ),
        new Set("Sodstvo", R.drawable.sets_24,
            "advokat", "braniti se", "brezposelnost", "detektiv", "dvomiti", "dvom", "glavna", "glavno", "goljufati", "inšpektor",
            "izdati", "kazen", "kaznovati", "krasti", "krivda", "krivec", "kriv", "morati", "nedolžen", "nujno", "obravnava", "obsodba",
            "obvezno", "pogojno", "policija", "pomagati", "pomoč", "posiliti", "postopek", "pričati", "priča", "primerno", "prisega",
            "siliti", "skriti", "skrivnost", "sodba", "sodišče", "soditi", "sodnik", "tožilec", "tožiti", "zaprt", "zaslišanje"
        ),
        new Set("Vojna", R.drawable.sets_25,
            "alarm", "bojevati se", "bomba", "bombardirati", "borba", "borec", "eksplozija", "pištola", "pobegniti", "puška", "rešiti",
            "spopad", "tank", "top", "ustreliti", "vojna"
        ),
        new Set("Denar", R.drawable.sets_26,
            "banka", "beračiti", "carina", "carina (plačilo)", "cestnina", "ček", "davek", "del", "denarnica", "denar", "devize",
            "devizni tečaj", "dobiček", "dolar", "doplačilo", "dragocen", "drug", "dvig", "hranilna knjižica", "hraniti", "lira",
            "loterija", "marka", "mošnja", "obrazec", "obresti", "obrok", "parkirnina", "plača", "polog", "položnica", "porabiti",
            "posoditi", "posojilo", "preživnina", "procent", "propad", "prosim", "prositi", "račun", "srečka", "stečaj", "šiling",
            "taksa", "tekoči račun", "tolar", "varčevati", "vrednost", "vstopnina", "zaklad", "zapraviti", "zaslužiti", "zaščita",
            "zaščititi", "zavarovalnina", "zavarovanje", "žepnina"
        ),
        new Set("Trgovina", R.drawable.sets_27,
            "cena", "dati", "dobiti", "drago", "kupiti", "plačati", "poceni", "podkupiti", "popust", "prodati", "razprodaja", "reklama",
            "samopostrežba", "trg", "trgovina", "zmanjkati"
        ),
        new Set("Religija", R.drawable.sets_28,
            "angel", "birma", "blagoslov", "bog", "božič", "cerkev", "duh", "duhovnik", "greh", "hudič", "Jezus", "kelih", "Kristus",
            "križ", "krst", "Marija", "maša", "Miklavž", "moliti", "nebesa", "nuna", "obhajilo", "oltar", "papež", "pekel",
            "poklekniti", "spoved", "sveti (versko)", "svetnik", "škof", "velika noč", "vera", "vrag", "zvonjenje", "župnik"
        ),
        new Set("Prosti čas", R.drawable.sets_29,
            "album", "balet", "bar", "boben", "cirkus", "čarati", "čarovnik", "darilo", "disko", "dogodki", "domine", "flavta",
            "folklora", "gramofon", "gugalnica", "gugalnik", "gusar", "harfa", "harmonika", "jubilej", "kitara", "klavir", "klovn",
            "koncert", "križanka", "loviti", "maska", "obletnica", "oder", "orkester", "palček", "ploskati", "prireditev", "proslava",
            "pust", "ritmika", "rojstni dan", "šala", "trobenta", "zabava", "zbor", "značka"
        ),
        new Set("Šport", R.drawable.sets_30,
            "akrobacija", "aktivnost", "atletika", "badminton", "bazen", "biljard", "bob", "boks", "boksati", "cilj", "čelada", "drsanje",
            "drsati", "dvorana", "ekipa", "gol", "golf", "golman", "hitrostno drsanje", "hokej", "jahanje", "judo", "karate", "kegljanje",
            "klub", "kolebnica", "kolesariti", "kolesarjenje", "kolo", "košarka", "kotalkanje", "krogla", "kultura", "lok", "lovec",
            "nagrada", "namizni tenis", "nastop", "nogomet", "nogometni vratar", "odbojka", "odlikovanje", "olimpiada", "piščalka",
            "plavanje", "plavati", "pokal", "poraz", "premagati", "prvenstvo", "rezultat", "ribolov", "rokomet", "sankanje", "slalom",
            "smučanje", "smučarski tek", "smučati", "smuči", "smuk", "stadion", "start", "streljanje", "streljati", "šah", "šport",
            "tekmovanje", "tek", "telovadba", "telovaditi", "trener", "trening", "trenirati", "turnir", "uspeh", "veleslalom", "veslanje",
            "zadeti", "zmagati", "zmaga", "žoga"
        ),
        new Set("Števila", R.drawable.sets_31,
            "deset", "devet", "devetdeset", "devetnajst", "devetsto", "drugi", "drugič", "dvaindvajset", "dvajset", "dvakrat", "dvanajst",
            "dve", "dvesto", "enaindvajset", "ena", "enajst", "enkrat", "milijarda", "milijon", "osem", "osemdeset", "osemnajst",
            "osemsto", "petdeset", "petkrat", "petnajst", "petsto", "pet", "polovica", "prvi", "prvič", "sedemdeset", "sedem",
            "sedemnajst", "sedemsto", "sto", "šestdeset", "šestkrat", "šest", "šestnajst", "šeststo", "štirideset", "štiri",
            "štirinajst", "štiristo", "štirje", "tisoč", "tretjič", "tretji", "tretjina", "trije", "trinajst", "tristo", "tri",
            "trideset", "trojno"
        ),
        new Set("Količina, velikost in stopnja", R.drawable.sets_32,
            "centimeter", "deciliter", "decimeter", "dekagram", "deliti", "deljenje", "do", "dodajanje", "dodati", "enačaj", "gram",
            "je enako", "kakovost", "kilogram", "kilometer", "kocka", "količina", "kos (enota)", "krat", "kubik", "kup", "kvadrat",
            "kvadratni koren", "liter", "majhno", "malo", "manjše", "meriti", "meter", "milimeter", "minus", "mnogo", "nič", "odšteti",
            "odštevanje", "odvzemanje", "odvzeti", "od", "ozko", "plus", "pravi kot", "premalo", "preveč", "promil", "računati",
            "sestaviti", "sešteti", "seštevanje", "skupaj", "široko", "šteti", "tehtati", "tehtnica", "tona", "večje", "vsota"
        ),
        new Set("Lastnost, vrsta in stanje", R.drawable.sets_33,
            "aktualno", "barva", "beda", "bela", "bogastvo", "bogat", "bolj", "boljše", "brez", "bronasta", "buden", "čisto", "črna",
            "črn", "črno", "čudovito", "dolg", "dolgo (časovno)", "dovolj", "drugače", "globoko", "gosto", "grd", "grdo", "hitro",
            "hlad", "hladno", "hrapavo", "hrup", "hrupno", "jasno", "javno", "kratek", "lahko", "ledeno", "lep", "lepo", "lepota",
            "ločeno", "majhen", "maksimum", "manj", "mastno", "mehkoba", "mehko", "minimum", "močno", "moderno", "modra", "mokro",
            "mraz", "mrzlo", "naj", "najboljše", "najslabše", "največ", "napačno", "naravno", "nasprotno", "natančno", "nemogoče",
            "neumno", "normalno", "noro", "nor", "novo", "oranžna", "ostro", "plitko", "počasi", "podobno", "polno", "pomembno",
            "popolno", "potrebno", "potrebovati", "površno", "prazno", "preprosto", "privatno", "raba", "rabiti", "različno", "rdeča",
            "redko", "reven", "revščina", "rjava", "ročno", "ropot", "ropotati", "roza", "rumena", "siromašen", "siromašnost", "siva",
            "slabo", "slabše", "službeno", "spati", "splošno", "spolzko", "srebrna", "starinsko", "strinjati se", "suho", "svež",
            "svoboda", "svoboden", "šibko", "temeljito", "temno", "težko", "točno", "toplo", "trdo", "trdota", "umazano", "umazati",
            "umetno", "umetnost", "važno", "več", "veliko", "velik", "vijolična", "vlažno", "vrelo", "vzporedno", "zadnji", "zanimivo",
            "zastarelo", "združeno", "združiti", "zelena", "zelo", "zlata"
        ),
        new Set("Države", R.drawable.sets_34,
            "Avstrija", "Hrvaška", "Italija", "Madžarska", "Slovenija"
        ),
        new Set("Mesta", R.drawable.sets_35,
            "Bled", "Celje", "Dravograd", "Gorica", "Koper", "Kranj", "Kranjska Gora", "Krško", "Ljubljana", "Maribor", "Murska Sobota",
            "Nova Gorica", "Novo mesto", "Piran", "Portorož", "Škofja Loka", "Trbovlje", "Triglav", "Velenje"
        ),
        new Set("Položaj, lega", R.drawable.sets_36,
            "blizu", "center", "daleč", "desno", "dno", "levo", "med", "nad", "naprej", "navzgor", "nazaj", "na", "navzdol", "nizko",
            "okoli", "pod", "proč", "proti", "rob", "skozi", "spodaj", "spredaj", "sredina", "stran", "tam", "tukaj", "visoko", "zgoraj",
            "znotraj", "zunaj"
        ),
        new Set("Abeceda", R.drawable.sets_37,
            "a", "b", "c", "č", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "š", "t", "u", "v", "w",
            "x", "y", "z", "ž"
        ),
        new Set("Neopredeljeno", R.drawable.sets_38,
            "bo", "dvojno", "gladko", "kljub", "kriza", "lastno", "leto", "lista", "listek", "meja", "metati", "nisem", "nov",
            "odpovedati", "odprto", "palica", "parkirati", "pihati", "pike", "postava", "prepovedano", "prisluhniti", "projicirati",
            "razjedati", "razmetano", "rjav", "sam", "samostojen", "sistem", "smeti", "vaja", "velikost", "vezava", "violina", "vrsta",
            "vse", "vzeti", "zadeva", "zasesti", "zavitek", "zaviti", "zebsti", "zlato", "zoprno", "zvoniti", "železo"
        ),
    };

    public static final Map<String, Set> SET_MAP = generateSetMap(SETS);

    private static Map<String, Set> generateSetMap(final Set[] sets) {
        final Map<String, Set> setMap = new HashMap<>(sets.length);
        for (final Set set : sets) {
            setMap.put(set.label, set);
        }
        return setMap;
    }
}
